/**
 * Utilidad administrativa para una traducción general de un diccionario.
 * Se Sacan los valores del diccionario más completo, se traduccen y se insertan en el resto de diccionarios, la traducción contiene algunos errores que deben repasarse individualmente.
 *  
 * @param {*} accion 
 * Valores para Acción ( mostrarTodo mostrarClaves mostrarValores escribirValores )
 * @param {*} diccionario 
 * Valores para Diccionario ( arrayES arrayGA arrayEN ... u otro array declarado )
 */
function actuarDiccionario(accion, diccionario) {

    var toret = "";
    var valoresNuevos = ['*',
        'Produciuse un erro ao conectar coa base de datos. Contacte co seu administrador',
        'Execución exitosa de SQL',
        "Erro ao executar SQL",
        "O conxunto de rexistros está baleiro",
        "O conxunto de rexistros non está baleiro",
        "Non podes cambiar un contrasinal que non sexa o teu propio",
        'Usuario conectado:',
        'español',
        'galego',
        "inglés",
        "ir a espazos",
        "Ir ás categorías",
        "Ir a actividades",
        "Ir a rexistros",
        "Ir a usuarios",
        "Vaia ao responsable",
        "ir á xente",
        "Ir a grupos",
        "Ir á configuración",
        'comezo',
        'Benvido',
        "Benvido á táboa de mostra de usuarios",
        "Benvido ao formulario de inserción",
        "Benvido ao formulario de busca",
        "Benvido ao formulario de edición",
        "Benvido ao formulario de eliminación",
        "Benvido ao formulario detallado",
        'Acceder',
        'Rexistro',
        "Recuperación de contrasinal",
        'Menú principal',
        "Introduza os seguintes datos",
        'Información persoal',
        "Datos de usuario",
        "Recuperar contrasinal",
        'O contrasinal deste usuario é: ',
        "Correo electrónico asociado co contrasinal",
        "Usuario propietario do contrasinal para recuperar",
        'ID do usuario',
        'ID do usuario',
        "Nome de usuario",
        'Contrasinal de usuario:',
        'Contrasinal de usuario:',
        'Novo contrasinal: ',
        'Repite o contrasinal',
        'ID do usuario',
        'Grupo',
        "Activo",
        "Accións",
        'Si',
        'Non',
        "Seleccione unha opción",
        "Nome do grupo",
        "Descrición do grupo",
        'ID responsable',
        "Currículo responsable",
        "Currículo responsable",
        "Cargar currículo",
        'Número de conta',
        "Activo",
        "Data de solicitude",
        "Documento de pago",
        "Día de pago",
        "Data de aceptación",
        "Activo",
        "Documento de pago",
        "Nome da actividade",
        "Bloqueo de maiúsculas",
        "Campo obrigatorio",
        'Entra',
        'Para rexistrarse',
        'Volver',
        'Pechar',
        'Conserva',
        'Buscar',
        'Editar',
        'Quitar',
        "Engadir",
        'Desconectar',
        "Engadir usuario",
        "Buscar usuarios",
        "Detalles do usuario",
        'Editar usuario',
        "Eliminar usuario",
        "Mostrar/Ocultar columnas",
        "Actualizar táboa",
        'ordenado',
        "OK",
        'Acceso',
        'Recuperar',
        "O usuario accedeu correctamente",
        "Sesión gardada en DB",
        "Sesión de base de datos eliminada e usuario desconectado",
        'O usuario non existe',
        "O contrasinal non é correcto",
        'A sesión non existe en DB',
        "Usuario con sesión activa",
        "Non se pode rexistrar porque o usuario xa existe",
        "Non se pode rexistrar porque o correo electrónico xa existe",
        "Erro de base de datos ao rexistrarse",
        "O identificador non pode estar baleiro",
        "O ID debe ter un máximo de 11 números: 11111111",
        'O DNI non pode estar baleiro.',
        'O DNI debe ter 8 números e unha letra.(11111111T)',
        "A letra introducida non se corresponde co número",
        "O campo do apelido non pode estar baleiro",
        "Os apelidos deben ter máis de 2 caracteres",
        "Os apelidos deben ter como máximo 100 caracteres",
        "Introduce os apelidos separados por espazos sen usar números nin símbolos",
        "O nome non pode estar baleiro",
        "Introduce o nome sen usar números nin símbolos",
        "O nome debe ter máis de 2 caracteres",
        "O nome debe ter menos de 46 caracteres",
        "A descrición non pode estar baleira",
        "Introduza a descrición sen usar números nin símbolos",
        "A descrición debe ter máis de 19 caracteres",
        "A descrición debe ter como máximo 200 caracteres",
        "A data non pode estar baleira",
        "A data de nacemento supera a actual",
        'Debes ser maior de idade.',
        "Cando nazas téntao de novo",
        "O número de conta non pode estar baleiro",
        "O número de conta non pode ter menos de 24 caracteres",
        "O número de conta non pode ter máis de 24 caracteres",
        "O formato do número de conta debe ser de 2 letras seguidas de 22 números",
        'Non se permiten caracteres que non sexan alfanuméricos ou º,ª,.,,',
        "O enderezo debe ter máis de 2 caracteres",
        "O enderezo debe ter menos de 200 caracteres",
        "O enderezo non pode estar baleiro",
        "Introduza o número de teléfono sen símbolos nin letras, exemplo: 111222333",
        "O campo non pode estar baleiro",
        "O teléfono non debe ter máis de 9 díxitos",
        "O teléfono non debe ter menos de 9 díxitos",
        'O correo electrónico non pode estar baleiro.',
        "O correo electrónico non pode ter menos de 3 caracteres",
        "O correo electrónico non pode exceder os 45 caracteres",
        "Formato de correo electrónico incorrecto, exemplo: enlafabricadesuenos@gmail.com",
        "O correo electrónico non pode ter menos de 5 caracteres",
        "O correo electrónico non pode exceder os 100 caracteres",
        'Os contrasinais deben coincidir',
        "O novo contrasinal é o mesmo que o antigo",
        "O inicio de sesión do usuario xa existe",
        'o ID de usuario xa existe',
        'O DNI debe existir persoalmente',
        "Non se pode modificar o ID de administrador",
        "Non se pode eliminar o administrador",
        "Erro ao inserir o usuario",
        "Erro ao modificar o usuario",
        "Produciuse un erro ao eliminar o usuario",
        'Erro de autenticación. Non estás autenticado',
        "Usuario inserido correctamente",
        "Usuario modificado correctamente",
        "Usuario eliminado correctamente",
        "Usuario rexistrado correctamente",
        "O usuario iniciou sesión correctamente",
        "O ID só debe ter ata 11 números, exemplo: 11111111",
        "DNI da persoa",
        "Nome da persoa",
        "Apelido da persoa",
        'Data de nacemento',
        "Enderezo da persoa",
        "Teléfono de persoa", "Correo electrónico da persoa",
        "Foto da persoa",
        'Cargar foto:',
        'Persoa celíaca',
        "Persoa inactiva",
        "O DNI xa existe en persoa",
        "O correo electrónico xa existe persoalmente",
        "A persoa a eliminar non existe",
        "Non se pode eliminar, hai un usuario con ese ID",
        "Produciuse un erro ao inserir a persoa, comprobe se hai posibles erros de formato ou se falta algún campo obrigatorio marcado con " * "",
        "Erro ao modificar a persoa",
        "Produciuse un erro ao eliminar a persoa",
        "Persoa inserida correctamente",
        "Persoa modificada correctamente",
        "Erro ao inserir o grupo",
        "Erro ao modificar o grupo",
        "Produciuse un erro ao eliminar o grupo",
        'Categoría',
        "Nome da categoría",
        "Descrición da categoría",
        'Espazo',
        'nome do espazo',
        'descrición do espazo',
        'identificador de actividade',
        "Descrición da actividade",
        "Prezo da actividade",
        "Non. Lugares",
        "Cor da actividade",
        "Cor do nome da actividade",
        "Erro ao inserir o usuario",
        "O inicio de sesión do usuario xa existe",
        'O usuario non existe',
        "O contrasinal non é correcto",
        "Non se pode rexistrar porque o correo electrónico xa existe",
        "Non se pode rexistrar porque o usuario xa existe",
        "Erro ao inserir o usuario",
        "Erro ao modificar o usuario",
        "Produciuse un erro ao eliminar o usuario",
        'Acceso denegado!!!!!!!!! Necesitas autenticarte',
        "Erro ao eliminar un usuario administrador",
        "Inserir correctamente o usuario",
        "Usuario modificado correctamente",
        "Usuario eliminado correctamente",
        "Usuario rexistrado correctamente",
        "O usuario iniciou sesión correctamente",
        "O tamaño do nome de usuario non pode ser inferior a 3",
        "O tamaño do nome de usuario non pode ser superior a 15",
        "O nome de usuario non pode conter máis que letras e números",
        "O tamaño do contrasinal do usuario non pode ser inferior a 3",
        "A lonxitude do contrasinal do usuario non pode ser superior a 16",
        "O contrasinal do usuario non pode conter máis que letras e números",
        'O nome e apelidos do usuario non poden ser inferiores a 3',
        'O nome e apelidos do usuario non poden ser superiores a 60',
        'O nome e apelidos do usuario non poden conter máis que letras',
        "O correo electrónico do usuario non pode ser inferior a 3",
        "O correo electrónico do usuario non pode ser superior a 40",
        "O correo electrónico do usuario non pode conter máis caracteres que os dun correo electrónico",
        "O administrador non pode ser diferente de si ou non",
        "Activo non pode ser diferente de si ou non",
        'A seguridade do contrasinal está comprometida. Contrasinal cifrado curto',
        'A seguridade do contrasinal está comprometida. Contrasinal cifrado longo',
        'A seguridade do contrasinal está comprometida. Non se permiten caracteres cifrados de contrasinal',
        "Proba",
        "Valor esperado",
        "Valor obtido",
        'Datos',
        'Éxito',
        'ID de rexistro',
        "O contrasinal cambiou correctamente",
        "Non se puido cambiar o contrasinal",
        "Este correo electrónico non está rexistrado",
        "Este correo electrónico non pertence a ese usuario",
        'Este DNI xa existe',
        'Este correo xa existe',
        "Non se pode editar o administrador",
        "Busca exitosa",
        "O nome de usuario xa existe",
        "Este ID de usuario non corresponde a ningunha persoa",
        "Usuario modificado correctamente",
        "Este ID de usuario xa existe",
        "O usuario que queres eliminar non existe",
        "O usuario non está autenticado",
        "O contrasinal cambiou correctamente",
        'Contrasinal incorrecto',
        "O nome de usuario non existe",
        "Grupo inserido correctamente",
        'O grupo xa existe',
        "Grupo modificado correctamente",
        "O grupo que queres eliminar ten usuarios asociados",
        "O grupo para eliminar non existe",
        "Eliminouse o grupo correctamente",
        "Categoría inserida correctamente",
        'Esta categoría xa existe',
        "Categoría modificada correctamente",
        "A categoría que se vai eliminar está asociada a unha actividade",
        'A categoría para eliminar non existe',
        "A categoría eliminouse correctamente",
        "Espazo inserido correctamente",
        'Este espazo xa existe',
        "Espazo modificado correctamente",
        "O espazo para eliminar está asociado a unha actividade",
        'O espazo para eliminar non existe',
        "Eliminouse o espazo correctamente",
        "Responsable inserido correctamente",
        'O responsable xa existe',
        "Responsable modificado correctamente",
        "Non existe o responsable da eliminación",
        "O responsable eliminouse correctamente",
        "Actividade inserida correctamente",
        "A actividade xa existe",
        'O espazo que queres non existe',
        "A categoría que queres asignar non existe",
        "Actividade modificada correctamente",
        'A actividade a eliminar non existe',
        "A actividade eliminouse correctamente",
        "Persoa eliminada correctamente",
        "Non se pode introducir espazo, comprobe se hai posibles erros de formato",
        "Non se pode introducir a categoría, comprobe se hai erros de formato en cada campo",
        "Formulario de inserción",
        "Editar formulario",
        "Formulario detallado",
        "Formulario de información",
        "Formulario de busca",
        "Formulario de cambio de contrasinal",
        'Datos de rexistro:',
        'Detalles do pagamento: ',
        "A data de pago non pode ser inferior á data da solicitude",
        "A data de aceptación non pode ser inferior á data de pagamento",
        'Usuarios',
        'grupos',
        'Responsable',
        'Persoas',
        'Espazos',
        'Categorías',
        "Actividades",
        'inscricións', 'Cambie o contrasinal',
        "O prezo non pode estar baleiro",
        'O prezo non pode conter máis de dous puntos',
        "O prezo non pode ser superior a 9999",
        "O valor decimal debe engadirse despois do punto",
        "A parte decimal non pode conter máis de 3 díxitos",
        "O prezo non pode ser superior a 9999,99",
        "O prezo non pode conter letras ou símbolos de puntuación que non sexan o punto",
        "O número de prazas non pode estar baleiro",
        "O número de asentos só pode ser números",
        "O número debe ser positivo",
        'A actividade non pode ter máis de 40 prazas',
        "O campo de cor non pode estar baleiro",
        "O campo de cor debe comezar por #",
        "O campo de cor non pode ter máis de 7 caracteres",
        "O campo de cor debe conter 6 caracteres que deben estar entre 0 e 9, e A e F en maiúsculas",
        "O campo de cor debe ter 7 caracteres",
        "O nome do ficheiro a cargar debe ter un máximo de 100 caracteres e un mínimo de 5",
        "O nome do ficheiro a cargar debe ter un máximo de 200 caracteres e un mínimo de 5",
        'Nome de usuario: ',
        'Nome de usuario: ',
        "Os contrasinais non coinciden",]
    switch (accion) {
        case 'mostrarTodo':
            //muestra todo el diccionario en formato clave:valor
            for (var clave in diccionario)
                toret = toret + '\n' + '\'' + clave + '\'' + ":" + '\'' + diccionario[clave] + '\',';
            console.log(toret);
            break;
        case 'mostrarClaves':
            for (var clave in diccionario)
                toret = toret + '\n' + '\'' + clave + '\',';
            console.log(toret);
            break;
        case 'mostrarValores':
            for (var clave in diccionario)
                toret = toret + '\n' + '\'' + diccionario[clave] + '\',';
            console.log(toret);
            break;
        case 'escribirValores':
            var i = 0;
            for (var clave in diccionario) {
                toret = toret + '\n' + '\'' + clave + '\'' + ':' + '\'' + valoresNuevos[i] + '\',';
                i++;
            }
            console.log(toret);
            break;
        case 'contar':
            var i = 0;
            for (var clave in diccionario) {
                i++;
            }
            console.log(i);
            break;
        default:
            console.log("escribirValores,mostrarValores,mostrarClaves,mostrarTodo")
            break;
    }
}
